version: "1.0"

services:
    # PaperMC
    paper:
        image: marctv/minecraft-papermc-server:latest
        restart: "no"
        environment:
            - MEMORYSIZE=1G
            - PAPERMC_FLAGS=""
        ports:
            - "25565:25565"
        volumes:
            - /home/skura/service/paper-dev:/data:rw \
        stdin_open: true
        tty: true
            
    # MariaDB
    db:
        restart: unless-stopped
        image: mariadb:10.7.3-focal
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/log:/var/log/mysql
            - ./db/init:/docker-entrypoint-initdb.d
        environment:
            TZ: 'Asia/Tokyo'
            MYSQL_ROOT_PASSWORD: 'root'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        
    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8889:80
        volumes:
            - ./phpmyadmin/sessions:/sessions
        depends_on:
            - "db"
