version: "1.0"

services:
  # PaperMC
  paper:
    image: marctv/minecraft-papermc-server:latest
    restart: "always"
    environment:
      - MEMORYSIZE=2G
      - PAPERMC_FLAGS=""
      # - PAPERMC_FLAGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      # - JAVAFLAGS=""
      - PUID=1000
      - PGID=1000
    ports:
      - "25565:25565"
      - "3000:3000"
      - "3002:8080"
    volumes:
      - /home/skura/service/paper-dev/server:/data:rw \
    stdin_open: true
    tty: true
    networks:
      - paperNetwork

  # MySQL
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - paperNetwork

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    ports:
      - "3001:80"
    networks:
      - paperNetwork

networks:
  paperNetwork:

volumes:
  db-data:
