version: "1.0"

services:
    # PaperMC
    paper:
        image: marctv/minecraft-papermc-server:latest
        restart: "no"
        environment:
            - MEMORYSIZE=2G
            - PAPERMC_FLAGS=""
            - PUID=1000
            - PGID=1000
        ports:
            - "25565:25565"
        volumes:
            - /home/skura/service/paper-dev:/data:rw \
        stdin_open: true
        tty: true
        networks:
            - paperNetwork

    # MariaDB
    db:
        container_name: mariaDB
        restart: unless-stopped
        image: mariadb:10.7.3-focal
        volumes:
            - /home/skura/service/paper-dev/db/data:/var/lib/mysql
            - /home/skura/service/paper-dev/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - /home/skura/service/paper-dev/db/log:/var/log/mysql
            - /home/skura/service/paper-dev/db/init:/docker-entrypoint-initdb.d
        environment:
            TZ: "Asia/Tokyo"
            MYSQL_ROOT_PASSWORD: "root"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        networks:
            - paperNetwork

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8889:80
        volumes:
            - /home/skura/service/paper-dev/phpmyadmin/sessions:/sessions
        depends_on:
            - "db"
        networks:
            - paperNetwork

networks:
    paperNetwork:
