version: "3.8"
services:
    mc:
        image: itzg/minecraft-server
        container_name: paper
        environment:
            EULA: "true"
            TYPE: PAPER
            VIEW_DISTANCE: 10
            MEMORY: 4G
        ports:
            - "25565:25565"
        volumes:
            - /home/skura/service/mc-multiplay:/data:rw \
        stdin_open: true
        tty: true
        restart: unless-stopped
