version: "3.3"

services:
  # nginx-proxy
  nginx-proxy:
    image: nginx
    environment:
      - MCSERVER_ADDR=${MCSERVER_ADDR}
    ports:
      - 19132:19132/udp
    command: /bin/sh -c "envsubst '$$MCSERVER_ADDR' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx-log:/var/log/nginx
